name: fake_store_prog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  dio: ^5.1.2
  injectable: ^2.5.2
  get_it: ^8.2.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.3
  go_router: ^16.2.5
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
    - family: Lora
      fonts:
      - asset: assets/fonts/Lora-SemiBold.ttf
        weight: 600
